module.exports = function(){
    return {
        letters:[
            {id:"1",name:"a"},
            {id:"2",name:"b"},
            {id:"3",name:"c"},
            {id:"4",name:"ç"},
            {id:"5",name:"d"},
            {id:"6",name:"e"},
            {id:"7",name:"f"},
            {id:"8",name:"g"},
            {id:"9",name:"ğ"},
            {id:"10",name:"h"},
            {id:"11",name:"ı"},
            {id:"12",name:"i"},
            {id:"13",name:"j"},
            {id:"14",name:"k"},
            {id:"15",name:"l"},
            {id:"16",name:"m"},
            {id:"17",name:"n"},
            {id:"18",name:"o"},
            {id:"19",name:"ö"},
            {id:"20",name:"p"},
            {id:"21",name:"r"},
            {id:"22",name:"s"},
            {id:"23",name:"ş"},
            {id:"24",name:"t"},
            {id:"25",name:"u"},
            {id:"26",name:"ü"},
            {id:"27",name:"v"},
            {id:"28",name:"y"},
            {id:"29",name:"z"}
        ]
    }}